### ISSUE TITLE
Deploy website on github pages

### ISSUE THREAD

**Issue by vikas924** [vikas924/Portfolio-setup-and-mobilefirst#6]
Hello there,

In this project, I have set up a "Portfolio-setup-and-mobilefirst" repository and deploy it on github pages. My tasks include:
 
1.Deploy repo on github pages.
2.Use https://vikas924.github.io/Portfolio-setup-and-mobilefirst/ to see website live.

**Comment by levy002** [comment]
## Hello @vikas924 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that doesn't follow the correct Gitfolow. Kindly make sure to create a pull request and submit the link on the dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
